name: rick_and_morty_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  bloc_test: ^9.1.3
  dio: ^5.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^8.0.2
  http_mock_adapter: ^0.4.4
  injector: ^2.0.0
  intl: ^0.18.1
  mocktail: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.5

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
